rem
rem   Setting up for a COMPILE of Time Line ....
rem
map s:=NOVA3/MCAL1:TL4
set m2mak=f:\m2exe
set m2sym=g:;f:\sym;f:\m2lib\sym
set m2obj=f:\obj;d:\m2lib\obj
set m2lib=f:\m2lib\lib
set m2ref=d:\ref;f:\m2lib\ref;s:\ref
set m2mod=d:\mod;f:\m2lib\mod;d:\testjig
set m2map=f:\map
set m2def=d:\def;f:\m2lib\def
set M2COPT=/DEBUG/R/S/T/O/OS
set M2LOPT=/DEBUG/MAP

set myname=AJL
set m2tmp=g:\

set TIMELINE=(Addin is (-tlems,-mac) user is ALAYMAN swapvol is G: memswap is G:)
